// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prueba_tecnica_net.Data;

#nullable disable

namespace Prueba_tecnica_net.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241116170431_PrimeraMigración")]
    partial class PrimeraMigración
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Prueba_tecnica_net.Models.BalanceResponsibleParty", b =>
                {
                    b.Property<string>("BrpCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BrpName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodingScheme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidityEnd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidityStart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrpCode");

                    b.ToTable("BalanceResponsibleParties");
                });
#pragma warning restore 612, 618
        }
    }
}
